### PR TITLE
remove all of the pages that have not been updated for 3.0 yet

### PR DESCRIPTION
**Pull request by GodloveD**
We should add these back in as they are updated for 3.0.  No need to duplicate the content that already exists in the 2.6 docs.

### CODE REVIEW

**Comment by devprincess** [comment]
Got it, I'll take a look at this now thanks @GodloveD :+1:

**Comment by GodloveD** [comment]
Looks like this change is already on the website. But the PR has not been merged.  🤔

**Comment by devprincess** [comment]
@GodloveD should I close this PR? it looks like it's already on the site

**Comment by GodloveD** [comment]
Yes.

**Pull request closed without merging**
